version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://yanling:password@db:5432/yanling_ctf
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    command: python app.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=yanling_ctf
      - POSTGRES_USER=yanling
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://yanling:password@db:5432/yanling_ctf
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    command: celery -A app.celery worker --loglevel=info

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: