"""Add author_id field to Challenge model

Revision ID: 946e6889e8f5
Revises: a57329555556
Create Date: 2025-09-16 12:10:21.655446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946e6889e8f5'
down_revision = 'a57329555556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_challenges_author_id', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_challenges_author_id', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
